"""Function and unit catalogue as listed by SMath Cloud (Insert Function / Insert Unit)."""

# (name, argument count (-1 = any), category, description)
FUNCTIONS = [('abs', 1, 'Unknown', 'abs("complexNumber") — Absolute value.'),
 ('acos', 1, 'Trigonometric', 'acos("complexNumber") — Returns the inverse cosine.'),
 ('acosh', 1, 'Hyperbolic', 'acosh("complexNumber") — Returns the inverse hyperbolic cosine.'),
 ('acot', 1, 'Trigonometric', 'acot("complexNumber") — Returns the inverse cotangent.'),
 ('acoth', 1, 'Hyperbolic', 'acoth("complexNumber") — Returns the inverse hyperbolic cotangent.'),
 ('acsc', 1, 'Trigonometric', 'acsc("complexNumber") — Returns the inverse cosecant.'),
 ('ainterp',
  3,
  'Unknown',
  'ainterp("1:argument", "2:argument", "3:argument") — Returns an Akima-spline interpolated y-value at '
  'x="3:argument" for data vectors x-vector "1:argument" and y-vector "2:argument" of the same size. (A '
  'vector is a column matrix.)'),
 ('alg',
  3,
  'Matrix and vector',
  'alg("1:matrix", "2:number", "3:number") — Cofactor (algebraically signed minor) of matrix.'),
 ('appVersion',
  1,
  'Unknown',
  'appVersion("argument") — Returns SMath Studio version. Supported values for "argument" are from -4 to 4. '
  'Negative argument requests for version of the program which last saved a worksheet. Positive argument '
  'requests for current SMath Studio instance version.'),
 ('arg',
  1,
  'Complex numbers',
  'arg("complexNumber") — Returns the angle from the real axis to the given complex number.'),
 ('asec', 1, 'Trigonometric', 'asec("complexNumber") — Returns the inverse secant.'),
 ('asin', 1, 'Trigonometric', 'asin("complexNumber") — Returns the inverse sine.'),
 ('asinh', 1, 'Hyperbolic', 'asinh("complexNumber") — Returns the inverse hyperbolic sine.'),
 ('atan', 1, 'Trigonometric', 'atan("complexNumber") — Returns the inverse tangent.'),
 ('atan', 2, 'Trigonometric', 'atan("1:complexNumber", "2:complexNumber") — Returns the inverse tangent.'),
 ('atanh', 1, 'Hyperbolic', 'atanh("complexNumber") — Returns the inverse hyperbolic tangent.'),
 ('augment',
  -1,
  'Matrix and vector',
  'augment(...) — Returns a matrix formed by placing the arguments left to right. Arguments are '
  'matrices/vectors having the same number of rows, or they are scalars and row matrices.'),
 ('ceil',
  1,
  'Unknown',
  'ceil("number") — The smallest integer that is greater than or equal to a given number.'),
 ('cinterp',
  3,
  'Unknown',
  'cinterp("1:argument", "2:argument", "3:argument") — Returns a cubic-spline interpolated y-value at '
  'x="3:argument" for data vectors x-vector "1:argument" and y-vector "2:argument" of the same size. (A '
  'vector is a column matrix.)'),
 ('Clear', -1, 'Programming', 'Clear(...) — Clear all variables and functions except the initial ones.'),
 ('col',
  2,
  'Matrix and vector',
  'col("1:matrix", "2:number") — Returns the specified column "2:number" of the matrix/vector "1:matrix".'),
 ('cols', 1, 'Matrix and vector', 'cols("matrix") — Returns the number of columns of the matrix/vector.'),
 ('concat', -1, 'Strings', 'concat(...) — Returns the string formed by concatenating the given strings.'),
 ('cos', 1, 'Trigonometric', 'cos("complexNumber") — Returns the cosine.'),
 ('cosh', 1, 'Hyperbolic', 'cosh("complexNumber") — Returns the hyperbolic cosine.'),
 ('cot', 1, 'Trigonometric', 'cot("complexNumber") — Returns the cotangent.'),
 ('coth', 1, 'Hyperbolic', 'coth("complexNumber") — Returns the hyperbolic cotangent.'),
 ('csc', 1, 'Trigonometric', 'csc("complexNumber") — Returns the cosecant.'),
 ('csch', 1, 'Hyperbolic', 'csch("complexNumber") — Returns the hyperbolic cosecant.'),
 ('csort',
  2,
  'Matrix and vector',
  'csort("1:matrix", "2:number") — Returns a matrix/vector "1:matrix" formed by rearranging rows until '
  'specified column "2:number" is in ascending order.'),
 ('description',
  1,
  'Strings',
  'description("name") — Returns Description text of the definition "name" using current language.'),
 ('det', 1, 'Matrix and vector', 'det("matrix") — Matrix determinant.'),
 ('dfile',
  1,
  'Files',
  'dfile("fileName") — Remove file from file system, if such file exists. The function returns \'1\' if '
  "successful, otherwise '0'."),
 ('diag',
  1,
  'Matrix and vector',
  'diag("number") — Returns a square matrix containing on its diagonal the elements of the given vector (a '
  'vector is a column matrix).'),
 ('diff',
  2,
  'Unknown',
  'diff("1:expression", "2:variable") — Finds the derivative of expression "1:expression" relative to '
  'variable "2:variable".'),
 ('diff',
  3,
  'Unknown',
  'diff("1:expression", "2:variable", "3:number") — Finds the order "3:number" derivative of expression '
  '"1:expression" relative to variable "2:variable".'),
 ('el',
  2,
  'Matrix and vector',
  'el("1:vector", "2:number") — Returns the specified element "2:number" of the vector "1:vector".'),
 ('el',
  3,
  'Matrix and vector',
  'el("1:matrix", "2:number", "3:number") — Returns the element of the matrix "1:matrix" in the row '
  '"2:number" and column "3:number".'),
 ('error',
  1,
  'Strings',
  'error("string") — Shows standard SMath Studio error tip with text from the function\'s argument.'),
 ('eval',
  1,
  'Unknown',
  'eval("expression") — Converts the given expression from symbolic to numeric notation.'),
 ('exp',
  1,
  'Unknown',
  'exp("complexNumber") — Returns the exponential function, e raised to the power "complexNumber".'),
 ('findrows',
  3,
  'Matrix and vector',
  'findrows("1:matrix", "2:expression", "3:number") — Retrieves all rows of the "1:matrix" where '
  '"2:expression" exists in column "3:number". Returns 0 if no matches found.'),
 ('findstr',
  2,
  'Strings',
  'findstr("1:string", "2:string") — Returns a vector (a column matrix) of the start positions of string '
  '"2:string" within string "1:string", or -1 if no matches found.'),
 ('floor',
  1,
  'Unknown',
  'floor("number") — The greatest integer that is less than or equal to a given number.'),
 ('for',
  3,
  'Programming',
  'for("1:increment", "2:expression", "3:expression") — For loop. The function of controlled iterations. The '
  'cycle repeats "3:expression", while "1:increment" uses all the values from "2:expression". Repeating '
  'expressions can be set to any number of expressions.'),
 ('for',
  4,
  'Programming',
  'for("1:increment", "2:condition", "3:expression", "4:expression") — For loop. The function of controlled '
  'iterations. The cycle repeats "4:expression", while "1:increment" satisfies the condition "2:condition" '
  'and after each passage necessarily satisfied "3:expression". Repeating expressions can be set to any '
  'number of expressions.'),
 ('Gamma', 1, 'Unknown', 'Gamma("number") — Gamma function.'),
 ('identity',
  1,
  'Matrix and vector',
  'identity("matrix") — Returns an n x n identity matrix (a matrix of 0\'s with 1\'s along the diagonal). '
  '"matrix" must be a positive integer.'),
 ('if',
  -1,
  'Programming',
  'if(...) — The IF construct allow execution of a statement or series of statements if the calculated '
  'expression is equal to 1 (true), or of a separate set of statements if it is 0 (false).'),
 ('Im', 1, 'Complex numbers', 'Im("complexNumber") — Returns the imaginary part of a complex number.'),
 ('importData',
  1,
  'Strings, Files',
  'importData("fileName") — Returns a matrix of loaded data from specified file using default parsing '
  'parameters.'),
 ('importData',
  9,
  'Strings, Files',
  'importData("1:fileName", "2:delimiter", "3:delimiter", "4:delimiter", "5:number", "6:number", "7:number", '
  '"8:number", "9:number") — Returns a matrix of loaded data from specified file "1:fileName". Function can '
  'be used with 1-9 of the arguments specified. Digit 0 (zero) can be used for the arguments (except '
  '"1:fileName") to get the built-in default values. Function is able to read data with manually specified '
  'Decimal Symbol ("2:delimiter"), Arguments Separator ("3:delimiter") and columns delimiters '
  '("4:delimiter"). To read a specific region of the data file rows an columns ranges can be requested '
  '("5:number" - start row, "6:number" - end row, "7:number" - start column, "8:number" - end column). To '
  'read a data represented symbolically "9:number" can be set to 1.'),
 ('int',
  4,
  'Unknown',
  'int("1:expression", "2:variable", "3:number", "4:number") — Definite integral of an expression '
  '"1:expression" with independent variable "2:variable". "3:number"-lower limit, "4:number"-upper limit.'),
 ('invert', 1, 'Matrix and vector', 'invert("matrix") — Inverted value.'),
 ('IsDefined',
  1,
  'Unknown',
  'IsDefined("expression") — Returns 1 if all variables and functions in the expression are defined, 0 - '
  'otherwise.'),
 ('IsString',
  1,
  'Strings',
  'IsString("expression") — Returns 1 if specified argument is a string. Returns 0 otherwise.'),
 ('Jacob',
  2,
  'Unknown',
  'Jacob("1:vector", "2:vector") — Returns the Jacobian matrix of the vector function "1:vector".'),
 ('length',
  1,
  'Matrix and vector',
  'length("matrix") — Returns the number of elements in the matrix or vector. Returns a scalar.'),
 ('line', -1, 'Programming', 'line(...) — For grouping 2 or more lines of code into a block.'),
 ('linterp',
  3,
  'Unknown',
  'linterp("1:argument", "2:argument", "3:argument") — Returns a linearly interpolated y-value at '
  'x="3:argument" for data vectors x-vector "1:argument" and y-vector "2:argument" of the same size. (A '
  'vector is a column matrix.)'),
 ('ln', 1, 'Unknown', 'ln("complexNumber") — Natural logarithm.'),
 ('log',
  2,
  'Unknown',
  'log("1:number", "2:number") — Returns the logarithm of "1:number" to the specified base "2:number".'),
 ('log10', 1, 'Unknown', 'log10("number") — Returns the base 10 logarithm of a number.'),
 ('mat', -1, 'Matrix and vector', 'mat(...) — Matrix.'),
 ('matrix',
  2,
  'Matrix and vector',
  'matrix("1:number", "2:number") — Returns a zero matrix of the specified size "1:number"-rows, '
  '"2:number"-columns.'),
 ('max',
  1,
  'Matrix and vector',
  'max("matrix") — Returns the largest element of vector or matrix. If any value is complex, returns '
  'max(Re(...)) + i*max(Im(...)).'),
 ('min',
  1,
  'Matrix and vector',
  'min("matrix") — Returns the smallest element of vector or matrix. If any value is complex, returns '
  'min(Re(...)) + i*min(Im(...)).'),
 ('minor', 3, 'Matrix and vector', 'minor("1:matrix", "2:number", "3:number") — Minor of matrix.'),
 ('mixed', 3, 'Unknown', 'mixed("1:number", "2:number", "3:number") — Mixed number.'),
 ('mod',
  2,
  'Unknown',
  'mod("1:number", "2:number") — Returns the remainder on dividing the "1:number" by "2:number". Arguments '
  'must be real.'),
 ('norm1', 1, 'Matrix and vector', 'norm1("matrix") — Returns the L1 norm of the matrix.'),
 ('norme', 1, 'Matrix and vector', 'norme("matrix") — Returns the Euclidean norm of the matrix.'),
 ('normi', 1, 'Matrix and vector', 'normi("matrix") — Returns the infinity norm of the matrix.'),
 ('nthroot', 2, 'Unknown', 'nthroot("1:complexNumber", "2:complexNumber") — Root.'),
 ('num2str', 1, 'Strings', 'num2str("expression") — Converts specified math expression to a string.'),
 ('num2str',
  2,
  'Strings',
  'num2str("1:expression", "2:string") — Converts specified math expression to a string.'),
 ('numden',
  1,
  'Unknown',
  'numden("expression") — Returns a 2-element vector (2x1 matrix) of the numerator and denominator of '
  '"expression".'),
 ('perc',
  2,
  'Unknown',
  'perc("1:number", "2:number") — Percent. For example, if "2:number" is 5 and "1:number" is 100, then this '
  'function returns 5% of 100.'),
 ('pol2xy',
  2,
  'Complex numbers',
  'pol2xy("1:argument", "2:argument") — Converts the polar coordinates of a point in 2D space to rectangular '
  'coordinates.'),
 ('polyroots',
  1,
  'Unknown',
  'polyroots("vector") — Returns the roots of the polynomial whose coefficients are in "vector".'),
 ('product',
  4,
  'Unknown',
  'product("1:expression", "2:increment", "3:number", "4:number") — Iterated product. Product of an '
  'expression "1:expression" in variable "2:increment" with lower limit "3:number" and upper limit '
  '"4:number".'),
 ('random',
  1,
  'Unknown',
  'random("number") — Returns a random number within the range of 0 to "number". Results are uniformly '
  'distributed within the range.'),
 ('range',
  2,
  'Unknown',
  'range("1:number", "2:number") — Returns a vector (column matrix) of values within the range of "1:number" '
  'to "2:number", inclusive. Each value is obtained by adding a step equal to 1 to the previous value, '
  'starting with "1:number". "2:number" does not necessarily appear in the output vector.'),
 ('range',
  3,
  'Unknown',
  'range("1:number", "2:number", "3:number") — Returns a vector (column matrix) of values within the range '
  'of "1:number" to "2:number", inclusive. Each value is obtained by adding a difference between "3:number" '
  'and "1:number". "2:number" does not necessarily appear in the output vector.'),
 ('rank', 1, 'Matrix and vector', 'rank("matrix") — Matrix rank.'),
 ('Re', 1, 'Complex numbers', 'Re("complexNumber") — Returns the real part of a complex number.'),
 ('reverse',
  1,
  'Matrix and vector',
  'reverse("matrix") — Reverses the order of rows in a matrix, or of elements in a vector. (A vector is a '
  'column matrix.)'),
 ('rfile',
  1,
  'Files',
  'rfile("fileName") — Read math expression from file, if such file exists. Often returns symbolic result.'),
 ('roots',
  2,
  'Unknown',
  'roots("1:vector", "2:vector") — Finds roots for system of nonlinear equations. Returns the values of '
  '"2:vector" to make the set of functions "1:vector" equal to zeros.'),
 ('roots',
  3,
  'Unknown',
  'roots("1:vector", "2:vector", "3:vector") — Finds roots for system of nonlinear equations according to '
  'specified approaches "3:vector". Returns the value of "2:vector" to make the set of functions "1:vector" '
  'equal to zeros.'),
 ('round',
  2,
  'Unknown',
  'round("1:number", "2:number") — Rounds the real number "1:number" to "2:number" places.'),
 ('round',
  3,
  'Unknown',
  'round("1:number", "2:number", "3:string") — Rounds the real number "1:number" to "2:number" places.'),
 ('row',
  2,
  'Matrix and vector',
  'row("1:matrix", "2:number") — Returns the specified row "2:number" of the matrix/vector "1:matrix".'),
 ('rows', 1, 'Matrix and vector', 'rows("matrix") — Returns the number of rows of the matrix/vector.'),
 ('rsort',
  2,
  'Matrix and vector',
  'rsort("1:matrix", "2:number") — Returns a matrix/vector "1:matrix" formed by rearranging columns until '
  'specified row "2:number" is in ascending order.'),
 ('sec', 1, 'Trigonometric', 'sec("complexNumber") — Returns the secant.'),
 ('sech', 1, 'Hyperbolic', 'sech("complexNumber") — Returns the hyperbolic secant.'),
 ('sign',
  1,
  'Unknown',
  'sign("number") — Returns 0 if x=0, 1 if x>0, and -1 otherwise. Argument must be a real number.'),
 ('sin', 1, 'Trigonometric', 'sin("complexNumber") — Returns the sine.'),
 ('sinh', 1, 'Hyperbolic', 'sinh("complexNumber") — Returns the hyperbolic sine.'),
 ('Sleep',
  1,
  'Programming',
  'Sleep("number") — Suspends the current thread for the specified amount of time specified in '
  'milliseconds.'),
 ('solve',
  2,
  'Unknown',
  'solve("1:expression", "2:variable") — Returns real roots of expression "1:expression" with respect to '
  'variable "2:variable".'),
 ('solve',
  4,
  'Unknown',
  'solve("1:expression", "2:variable", "3:number", "4:number") — Returns real roots of expression '
  '"1:expression" with respect to variable "2:variable" in the interval between "3:number" and "4:number".'),
 ('sort',
  1,
  'Matrix and vector',
  'sort("matrix") — Returns a vector with the values sorted in ascending order. (A vector is a column '
  'matrix.)'),
 ('sqrt', 1, 'Unknown', 'sqrt("complexNumber") — Square root.'),
 ('stack',
  -1,
  'Matrix and vector',
  'stack(...) — Returns an array formed by placing arguments top to bottom. Arguments are matrices/vectors '
  'having the same number of columns, or they are scalars and vectors. (A vector is a column matrix.)'),
 ('str2num',
  1,
  'Strings',
  'str2num("string") — Returns math expression formed by converting from specified string.'),
 ('strlen', 1, 'Strings', 'strlen("string") — Returns the number of characters in specified string.'),
 ('strrep',
  3,
  'Strings',
  'strrep("1:string", "2:string", "3:string") — Replaces all occurrences of the string "2:string" within '
  'string "1:string" with the string "3:string".'),
 ('submatrix',
  5,
  'Matrix and vector',
  'submatrix("1:matrix", "2:argument", "3:argument", "4:argument", "5:argument") — Returns the submatrix '
  'consisting of elements in rows "2:argument" through "3:argument" and columns "4:argument" through '
  '"5:argument".'),
 ('substr',
  2,
  'Strings',
  'substr("1:string", "2:number") — Returns a substring of "1:string". "2:number" is a starting character '
  'position of substring.'),
 ('substr',
  3,
  'Strings',
  'substr("1:string", "2:number", "3:number") — Returns a substring of "1:string". Where "2:number" is a '
  'starting character position of substring; "3:number" is a length of result string.'),
 ('sum', 1, 'Unknown', 'sum("matrix") — Summation of the vector/matrix elements.'),
 ('sum',
  4,
  'Unknown',
  'sum("1:expression", "2:increment", "3:number", "4:number") — Summation of an expression "1:expression" in '
  'summation variable "2:increment" with lower limit "3:number" and upper limit "4:number".'),
 ('sys', -1, 'Unknown', 'sys(...) — System of values or equations.'),
 ('tan', 1, 'Trigonometric', 'tan("complexNumber") — Returns the tangent.'),
 ('tanh', 1, 'Hyperbolic', 'tanh("complexNumber") — Returns the hyperbolic tangent.'),
 ('time',
  1,
  'Programming',
  'time("argument") — Returns the number of milliseconds that have elapsed since 12:00 midnight, January 1, '
  '1601 A.D.'),
 ('tr',
  1,
  'Matrix and vector',
  'tr("matrix") — Matrix trace - sum of the elements on the main diagonal (the diagonal from the upper left '
  'to the lower right) of a square matrix.'),
 ('trace',
  -1,
  'Programming',
  'trace(...) — Returns a string containing the value of the arguments with output order and surrounding '
  'text specified by first argument. Outputs values in the Output Window. Specifying of the first text '
  'argument is optional.'),
 ('transpose', 1, 'Matrix and vector', 'transpose("matrix") — Matrix transpose.'),
 ('trunc',
  1,
  'Unknown',
  'trunc("number") — Returns the integer part of a real number "number" by removing the fractional part.'),
 ('try',
  2,
  'Programming',
  'try("1:argument", "2:argument") — Try/on error statement. The function evaluates and returns '
  '"1:argument". If "1:argument" throws an error, the function evaluates and returns "2:argument".'),
 ('UnitsOf',
  1,
  'Unknown',
  'UnitsOf("argument") — Returns the units of "argument". If "argument" has no units, returns 1.'),
 ('vectorize',
  1,
  'Matrix and vector',
  'vectorize("expression") — Allows to perform the same operation on each element of a vector, matrix or '
  'system.'),
 ('vminor',
  3,
  'Matrix and vector',
  'vminor("1:matrix", "2:number", "3:number") — Returns submatrix with the specified row ("2:number") and '
  'column ("3:number") removed from the given matrix ("1:matrix").'),
 ('wfile',
  2,
  'Files',
  'wfile("1:expression", "2:fileName") — Write math expression "1:expression" to a file "2:fileName". If a '
  'file with the given "2:fileName" exists, it will be overwritten. The function returns \'1\' if '
  "successful, otherwise '0'."),
 ('while',
  2,
  'Programming',
  'while("1:condition", "2:expression") — A function for iterating. The loop body, "2:expression" is '
  'repeatedly executed as long as the condition "1:condition" is true. Multiple expressions can be included '
  'in "2:expression" by means of the line(...) function.'),
 ('xy2pol',
  2,
  'Complex numbers',
  'xy2pol("1:argument", "2:argument") — Converts the rectangular coordinates of a point in 2D space to polar '
  'coordinates.')]

# unit -> (category, title)
UNIT_CATALOG = {'"': ('Dimensionless', 'Second of arc'),
 '%': ('Dimensionless', 'Percentage'),
 "'": ('Dimensionless', 'Minute of arc'),
 'A': ('Electric current', 'Ampere'),
 'Angstrom': ('Length', 'Angstrom'),
 'B': ('Information', 'Byte'),
 'BTU': ('Energy', 'British thermal unit'),
 'Bq': ('Frequency', 'Becquerel'),
 'C': ('Charge', 'Coulomb'),
 'Ci': ('Frequency', 'Curie'),
 'D': ('Dipole moment', 'Debye'),
 'F': ('Capacitance', 'Farad'),
 'Fd': ('Charge', 'Faraday'),
 'Fr': ('Charge', 'Franklin (Statcoulomb)'),
 'G': ('Magnetic flux density', 'Gauss'),
 'G.N': ('Physical constants', 'Newtonian constant of gravitation'),
 'GB': ('Information', 'Gigabyte'),
 'GBq': ('Frequency', 'Gigabecquerel'),
 'GHz': ('Frequency', 'Gigahertz'),
 'GJ': ('Energy', 'Gigajoule'),
 'GN': ('Force', 'Giganewton'),
 'GPa': ('Pressure', 'Gigapascal'),
 'GW': ('Power', 'Gigawatt'),
 'Gbit': ('Information', 'Gigabit'),
 'GeV': ('Energy', 'Gigaelectronvolt'),
 'Gi': ('Electric current', 'Gilbert'),
 'GiB': ('Information', 'Gibibyte'),
 'Gy': ('Dose', 'Gray'),
 'H': ('Inductance', 'Henry'),
 'Hz': ('Frequency', 'Hertz'),
 'J': ('Energy', 'Joule'),
 'K': ('Temperature', 'Kelvin'),
 'L': ('Volume', 'Liter'),
 'MB': ('Information', 'Megabyte'),
 'MBq': ('Frequency', 'Megabecquerel'),
 'MHz': ('Frequency', 'Megahertz'),
 'MJ': ('Energy', 'Megajoule'),
 'MN': ('Force', 'Meganewton'),
 'MPa': ('Pressure', 'Megapascal'),
 'MW': ('Power', 'Megawatt'),
 'Mbit': ('Information', 'Megabit'),
 'MeV': ('Energy', 'Megaelectronvolt'),
 'Mg': ('Mass', 'Megagram'),
 'MiB': ('Information', 'Mebibyte'),
 'Mohm': ('Resistance', 'Megohm'),
 'Mx': ('Magnetic flux', 'Maxwell'),
 'MΩ': ('Resistance', 'Megohm'),
 'N': ('Force', 'Newton'),
 'N.A': ('Physical constants', "Avogadro's number"),
 'Oe': ('Magnetic field strength', 'Oersted'),
 'P': ('Viscosity, dynamic', 'Poise'),
 'Pa': ('Pressure', 'Pascal'),
 'R': ('Radiation, exposure to gamma or x-rays', 'Roentgen'),
 'R.m': ('Physical constants', 'Gas constant'),
 'S': ('Electric conductance or admittance', 'Siemens'),
 'Smoot': ('Length', 'Smoot'),
 'St': ('Viscosity, kinematic', 'Stokes'),
 'Sv': ('Dose', 'Sievert'),
 'T': ('Magnetic flux density', 'Tesla'),
 'TB': ('Information', 'Terabyte'),
 'THz': ('Frequency', 'THz'),
 'TJ': ('Energy', 'Terajoule'),
 'TN': ('Force', 'Teranewton'),
 'Tbit': ('Information', 'Terabit'),
 'TeV': ('Energy', 'Teraelectronvolt'),
 'TiB': ('Information', 'Tebibyte'),
 'V': ('Potential', 'Volt'),
 'W': ('Power', 'Watt'),
 'Wb': ('Magnetic flux', 'Weber'),
 'a': ('Area', 'Are'),
 'acre': ('Area', 'Acre'),
 'arcmin': ('Dimensionless', 'Minute of arc'),
 'arcsec': ('Dimensionless', 'Second of arc'),
 'atm': ('Pressure', 'Atmosphere'),
 'atom': ('Substance', 'Atom'),
 'au': ('Length', 'Astronomical unit'),
 'bar': ('Pressure', 'Bar'),
 'barn': ('Area', 'Barns'),
 'bit': ('Information', 'Bit'),
 'bohr': ('Length', 'Bohr'),
 'byte': ('Information', 'Byte'),
 'c': ('Velocity', 'Speed of light'),
 'ca': ('Area', 'Centiare'),
 'cal': ('Energy', 'Calorie'),
 'cd': ('Luminous intensity', 'Candela'),
 'cm': ('Length', 'Centimeter'),
 'ct': ('Mass', 'Metric carat'),
 'dB': ('Noise level', 'Decibel'),
 'dS': ('Electric conductance or admittance', 'Decisiemens'),
 'daB': ('Noise level', 'Dekabel'),
 'daa': ('Area', 'Decare'),
 'day': ('Time', 'Day'),
 'deg': ('Dimensionless', 'Degree'),
 'den': ('Linear density', 'Denier'),
 'dm': ('Length', 'Decimeter'),
 'dpi': ('Resolution', 'Dots per inch'),
 'dyn': ('Force', 'Dyne'),
 'dyne': ('Force', 'Dyne'),
 'e': ('Charge', 'Elementary charge'),
 'eV': ('Energy', 'Electronvolt'),
 'erg': ('Energy', 'Unit of energy and mechanical work'),
 'farad': ('Capacitance', 'Farad'),
 'faraday': ('Charge', 'Faraday'),
 'ft': ('Length', 'Foot'),
 'furlong': ('Length', 'Furlong'),
 'g': ('Mass', 'Gram'),
 'g.e': ('Acceleration', 'Gravitational acceleration'),
 'gal': ('Volume', 'Gallon'),
 'gauss': ('Magnetic flux density', 'Gauss'),
 'gf': ('Force', 'Gram-force'),
 'gon': ('Dimensionless', 'Grad - gon'),
 'grad': ('Dimensionless', 'Grad - gon'),
 'gram': ('Mass', 'Gram'),
 'h': ('Physical constants', 'Planck constant'),
 'ha': ('Area', 'Hectare'),
 'henry': ('Inductance', 'Henry'),
 'hhp': ('Power', 'Water Horsepower'),
 'hildebrand': ('Physical constants', 'Hildebrand, solubility parameter'),
 'hp': ('Power', 'Horsepower'),
 'hr': ('Time', 'Hour'),
 'in': ('Length', 'Inch'),
 'inHg': ('Pressure', 'Inch of mercury'),
 'joule': ('Energy', 'Joule'),
 'k': ('Physical constants', 'Boltzmann constant'),
 'kA': ('Electric current', 'Kiloampere'),
 'kB': ('Information', 'Kilobyte'),
 'kBq': ('Frequency', 'Kilobecquerel'),
 'kHz': ('Frequency', 'Kilohertz'),
 'kJ': ('Energy', 'Kilojoule'),
 'kN': ('Force', 'Kilonewton'),
 'kPa': ('Pressure', 'Kilopascal'),
 'kV': ('Potential', 'Kilovolt'),
 'kW': ('Power', 'Kilowatt'),
 'kat': ('Catalytic activity', 'Katal'),
 'katal': ('Catalytic activity', 'Katal'),
 'kbit': ('Information', 'Kilobit'),
 'kcal': ('Energy', 'Kilocalorie'),
 'keV': ('Energy', 'Electronvolt'),
 'kg': ('Mass', 'Kilogram'),
 'kgf': ('Force', 'Kilogram Force'),
 'kiB': ('Information', 'Kibibyte'),
 'kip': ('Force', 'Kip'),
 'klm': ('Luminous flux', 'klm'),
 'klx': ('Illuminance or luminous flux density', 'klx'),
 'km': ('Length', 'Kilometer'),
 'kmol': ('Substance', 'Kilomole'),
 'kn': ('Velocity', 'Knot'),
 'knot': ('Velocity', 'Knot'),
 'kohm': ('Resistance', 'Kilohm'),
 'kph': ('Velocity', 'Kilometers per hour'),
 'kpsi': ('Pressure', 'kpsi'),
 'ks': ('Time', 'Kilosecond'),
 'ksf': ('Pressure', 'Kilo-pounds-force per square foot'),
 'ksi': ('Pressure', 'Kilo-pounds-force per square inch'),
 'kΩ': ('Resistance', 'Kilohm'),
 'lb': ('Mass', 'Pound'),
 'lb.m': ('Mass', 'Pound'),
 'lbf': ('Force', 'Pound-force'),
 'lbm': ('Mass', 'Pound'),
 'lbmol': ('Substance', 'Pound-mole'),
 'lm': ('Luminous flux', 'Lumen'),
 'lx': ('Illuminance or luminous flux density', 'Lux'),
 'ly': ('Length', 'Light-year'),
 'm': ('Length', 'Meter'),
 'm.e': ('Mass', 'Electron mass'),
 'm.n': ('Mass', 'Neutron mass'),
 'm.p': ('Mass', 'Proton mass'),
 'mA': ('Electric current', 'Milliampere'),
 'mC': ('Charge', 'Millicoulomb'),
 'mCi': ('Frequency', 'Millicurie'),
 'mF': ('Capacitance', 'Millifarad'),
 'mH': ('Inductance', 'Millihenry'),
 'mJ': ('Energy', 'Millijoule'),
 'mL': ('Volume', 'Milliliter'),
 'mN': ('Force', 'Millinewton'),
 'mR': ('Radiation, exposure to gamma or x-rays', 'Milliroentgen'),
 'mS': ('Electric conductance or admittance', 'Millisiemens'),
 'mT': ('Magnetic flux density', 'mT'),
 'mV': ('Potential', 'Millivolt'),
 'mW': ('Power', 'Milliwatt'),
 'mWb': ('Magnetic flux', 'mWb'),
 'mg': ('Mass', 'Milligram'),
 'mi': ('Length', 'Mile'),
 'micron': ('Length', 'Micrometer'),
 'mile': ('Length', 'Mile'),
 'min': ('Time', 'Minute'),
 'mm': ('Length', 'Millimeter'),
 'mmHg': ('Pressure', 'Torr'),
 'mmol': ('Substance', 'Millimole'),
 'mohm': ('Resistance', 'Milliohm'),
 'mol': ('Substance', 'Mole'),
 'month': ('Time', 'Month'),
 'mph': ('Velocity', 'Miles per hour'),
 'ms': ('Time', 'Millisecond'),
 'mΩ': ('Resistance', 'Milliohm'),
 'nA': ('Electric current', 'Nanoampere'),
 'nC': ('Charge', 'Nanocoulomb'),
 'nF': ('Capacitance', 'Nanofarad'),
 'nH': ('Inductance', 'Nanohenry'),
 'nJ': ('Energy', 'nJ'),
 'nN': ('Force', 'nN'),
 'nV': ('Potential', 'Nanovolt'),
 'nW': ('Power', 'Nanowatt'),
 'nm': ('Length', 'Nanometer'),
 'nmi': ('Length', 'Nautical mile'),
 'nmol': ('Substance', 'nmol'),
 'ns': ('Time', 'Nanosecond'),
 'nt': ('Luminance', 'Nit'),
 'ohm': ('Resistance', 'Ohm'),
 'ounce': ('Mass', 'Ounce'),
 'oz': ('Mass', 'Ounce'),
 'pA': ('Electric current', 'Picoampere'),
 'pC': ('Charge', 'Picocoulomb'),
 'pF': ('Capacitance', 'Picofarad'),
 'pJ': ('Energy', 'pJ'),
 'pN': ('Force', 'pN'),
 'pS': ('Electric conductance or admittance', 'Picosiemens'),
 'pV': ('Potential', 'Picovolt'),
 'pW': ('Power', 'Picowatt'),
 'pc': ('Length', 'Parsec'),
 'pm': ('Length', 'Picometer'),
 'poise': ('Viscosity, dynamic', 'Poise'),
 'pound': ('Mass', 'Pound'),
 'ppb': ('Dimensionless', 'Parts per billion'),
 'ppm': ('Dimensionless', 'Parts per million'),
 'ps': ('Time', 'Picosecond'),
 'psf': ('Pressure', 'Pounds-force per square foot'),
 'psi': ('Pressure', 'Pounds-force per square inch'),
 'rad': ('Dimensionless', 'Radian'),
 'radpm': ('Frequency', 'Radians per minute'),
 'rev': ('Dimensionless', 'Revolution'),
 'rph': ('Frequency', 'Revolutions per hour'),
 'rpm': ('Frequency', 'Revolutions per minute'),
 's': ('Time', 'Second'),
 'sb': ('Luminance', 'Stilb'),
 'sec': ('Time', 'Second'),
 'slug': ('Mass', 'Slug'),
 'sr': ('Solid angle', 'Steradian'),
 'statC': ('Charge', 'Franklin (Statcoulomb)'),
 'stokes': ('Viscosity, kinematic', 'Stokes'),
 't': ('Mass', 'Metric ton'),
 'tesla': ('Magnetic flux density', 'Tesla'),
 'ton': ('Mass', 'Ton'),
 'tonf': ('Force', 'Ton Force'),
 'tonne': ('Mass', 'Metric ton'),
 'tonnef': ('Force', 'Metric Ton Force'),
 'torr': ('Pressure', 'Torr'),
 'u': ('Mass', 'Unified atomic mass unit - dalton'),
 'volt': ('Potential', 'Volt'),
 'watt': ('Power', 'Watt'),
 'week': ('Time', 'Week'),
 'yd': ('Length', 'Yard'),
 'yr': ('Time', 'Year'),
 '¤': ('Money', 'Default currency'),
 '°': ('Dimensionless', 'Degree'),
 '°C': ('Temperature', 'Celsius'),
 '°F': ('Temperature', 'Fahrenheit'),
 '°Ra': ('Temperature', 'Rankine'),
 '°Re': ('Temperature', 'Réaumur'),
 'Å': ('Length', 'Angstrom'),
 'Δ°C': ('Temperature', 'Change °C'),
 'Δ°F': ('Temperature', 'Change °F'),
 'Δ°Re': ('Temperature', 'Change °Re'),
 'Ω': ('Resistance', 'Ohm'),
 'ε.0': ('Physical constants', 'Vacuum permittivity'),
 'μ.0': ('Physical constants', 'Magnetic constant'),
 'μA': ('Electric current', 'Microampere'),
 'μC': ('Charge', 'Microcoulomb'),
 'μCi': ('Frequency', 'Microcurie'),
 'μF': ('Capacitance', 'Microfarad'),
 'μH': ('Inductance', 'Microhenry'),
 'μJ': ('Energy', 'μJ'),
 'μN': ('Force', 'Micronewton'),
 'μR': ('Radiation, exposure to gamma or x-rays', 'Microroentgen'),
 'μS': ('Electric conductance or admittance', 'Microsiemens'),
 'μT': ('Magnetic flux density', 'μT'),
 'μV': ('Potential', 'Microvolt'),
 'μW': ('Power', 'Microwatt'),
 'μWb': ('Magnetic flux', 'μWb'),
 'μg': ('Mass', 'Microgram'),
 'μm': ('Length', 'Micrometer'),
 'μmol': ('Substance', 'Micromole'),
 'μs': ('Time', 'Microsecond'),
 '‰': ('Dimensionless', 'Per mille')}
