"""Excel's own names for the arguments of its functions, as its formula tip
shows them (optional ones in brackets; "…" repeats the one before)."""

ARGS = {
    "ABS": "number", "ACOS": "number", "ACOSH": "number", "AGGREGATE": "function_num, options, ref1, …",
    "AND": "logical1, [logical2], …", "ASIN": "number", "ATAN": "number", "ATAN2": "x_num, y_num",
    "AVERAGE": "number1, [number2], …", "AVERAGEA": "value1, [value2], …",
    "AVERAGEIF": "range, criteria, [average_range]",
    "AVERAGEIFS": "average_range, criteria_range1, criteria1, [criteria_range2, criteria2], …",
    "BYCOL": "array, lambda", "BYROW": "array, lambda", "CEILING": "number, significance",
    "CEILING.MATH": "number, [significance], [mode]", "CHAR": "number", "CHOOSE": "index_num, value1, [value2], …",
    "CHOOSECOLS": "array, col_num1, [col_num2], …", "CHOOSEROWS": "array, row_num1, [row_num2], …",
    "CLEAN": "text", "CODE": "text", "COLUMN": "[reference]", "COLUMNS": "array", "COMBIN": "number, number_chosen",
    "CONCAT": "text1, [text2], …", "CONCATENATE": "text1, [text2], …", "CONVERT": "number, from_unit, to_unit",
    "CORREL": "array1, array2", "COS": "number", "COSH": "number", "COUNT": "value1, [value2], …",
    "COUNTA": "value1, [value2], …", "COUNTBLANK": "range", "COUNTIF": "range, criteria",
    "COUNTIFS": "criteria_range1, criteria1, [criteria_range2, criteria2], …",
    "DATE": "year, month, day", "DATEDIF": "start_date, end_date, unit", "DATEVALUE": "date_text",
    "DAY": "serial_number", "DAYS": "end_date, start_date", "DEGREES": "angle", "DROP": "array, rows, [columns]",
    "EDATE": "start_date, months", "EOMONTH": "start_date, months", "EVEN": "number", "EXACT": "text1, text2",
    "EXP": "number", "FACT": "number", "FILTER": "array, include, [if_empty]",
    "FIND": "find_text, within_text, [start_num]", "FIXED": "number, [decimals], [no_commas]",
    "FLOOR": "number, significance", "FLOOR.MATH": "number, [significance], [mode]",
    "FORECAST": "x, known_y's, known_x's", "FORECAST.LINEAR": "x, known_y's, known_x's",
    "FV": "rate, nper, pmt, [pv], [type]", "GROWTH": "known_y's, [known_x's], [new_x's], [const]",
    "HLOOKUP": "lookup_value, table_array, row_index_num, [range_lookup]", "HOUR": "serial_number",
    "HSTACK": "array1, [array2], …", "IF": "logical_test, [value_if_true], [value_if_false]",
    "IFERROR": "value, value_if_error", "IFNA": "value, value_if_na",
    "IFS": "logical_test1, value_if_true1, [logical_test2, value_if_true2], …",
    "INDEX": "array, row_num, [column_num]", "INDIRECT": "ref_text, [a1]", "INT": "number",
    "INTERCEPT": "known_y's, known_x's", "IPMT": "rate, per, nper, pv, [fv], [type]", "IRR": "values, [guess]",
    "ISBLANK": "value", "ISERROR": "value", "ISNUMBER": "value", "ISTEXT": "value", "LAMBDA": "[parameter1, …], calculation",
    "LARGE": "array, k", "LEFT": "text, [num_chars]", "LEN": "text", "LET": "name1, name_value1, calculation_or_name2, …",
    "LINEST": "known_y's, [known_x's], [const], [stats]", "LN": "number", "LOG": "number, [base]", "LOG10": "number",
    "LOOKUP": "lookup_value, lookup_vector, [result_vector]", "LOWER": "text", "MAKEARRAY": "rows, cols, lambda",
    "MAP": "array1, [array2], …, lambda", "MATCH": "lookup_value, lookup_array, [match_type]",
    "MAX": "number1, [number2], …", "MAXIFS": "max_range, criteria_range1, criteria1, …",
    "MEDIAN": "number1, [number2], …", "MID": "text, start_num, num_chars", "MIN": "number1, [number2], …",
    "MINIFS": "min_range, criteria_range1, criteria1, …", "MINUTE": "serial_number", "MMULT": "array1, array2",
    "MOD": "number, divisor", "MONTH": "serial_number", "MROUND": "number, multiple", "NETWORKDAYS": "start_date, end_date, [holidays]",
    "NORM.DIST": "x, mean, standard_dev, cumulative", "NORM.INV": "probability, mean, standard_dev",
    "NORM.S.DIST": "z, cumulative", "NORM.S.INV": "probability", "NOT": "logical", "NOW": "", "NPER": "rate, pmt, pv, [fv], [type]",
    "NPV": "rate, value1, [value2], …", "ODD": "number", "OFFSET": "reference, rows, cols, [height], [width]",
    "OR": "logical1, [logical2], …", "PERCENTILE": "array, k", "PI": "", "PMT": "rate, nper, pv, [fv], [type]",
    "POWER": "number, power", "PPMT": "rate, per, nper, pv, [fv], [type]", "PRODUCT": "number1, [number2], …",
    "PROPER": "text", "PV": "rate, nper, pmt, [fv], [type]", "QUARTILE": "array, quart", "RADIANS": "angle",
    "RAND": "", "RANDBETWEEN": "bottom, top", "RANK": "number, ref, [order]", "RANK.AVG": "number, ref, [order]",
    "RANK.EQ": "number, ref, [order]", "RATE": "nper, pmt, pv, [fv], [type], [guess]", "REDUCE": "[initial_value], array, lambda",
    "REPLACE": "old_text, start_num, num_chars, new_text", "REPT": "text, number_times", "RIGHT": "text, [num_chars]",
    "ROUND": "number, num_digits", "ROUNDDOWN": "number, num_digits", "ROUNDUP": "number, num_digits",
    "ROW": "[reference]", "ROWS": "array", "SCAN": "[initial_value], array, lambda",
    "SEARCH": "find_text, within_text, [start_num]", "SECOND": "serial_number",
    "SEQUENCE": "rows, [columns], [start], [step]", "SIGN": "number", "SIN": "number", "SINH": "number",
    "SLOPE": "known_y's, known_x's", "SMALL": "array, k", "SORT": "array, [sort_index], [sort_order], [by_col]",
    "SORTBY": "array, by_array1, [sort_order1], …", "SQRT": "number", "STDEV": "number1, [number2], …",
    "STDEV.P": "number1, [number2], …", "STDEV.S": "number1, [number2], …",
    "SUBSTITUTE": "text, old_text, new_text, [instance_num]", "SUBTOTAL": "function_num, ref1, [ref2], …",
    "SUM": "number1, [number2], …", "SUMIF": "range, criteria, [sum_range]",
    "SUMIFS": "sum_range, criteria_range1, criteria1, [criteria_range2, criteria2], …",
    "SUMPRODUCT": "array1, [array2], …", "SUMSQ": "number1, [number2], …",
    "SWITCH": "expression, value1, result1, [default_or_value2, result2], …", "TAKE": "array, rows, [columns]",
    "TAN": "number", "TANH": "number", "TEXT": "value, format_text", "TEXTAFTER": "text, delimiter, [instance_num], …",
    "TEXTBEFORE": "text, delimiter, [instance_num], …", "TEXTJOIN": "delimiter, ignore_empty, text1, [text2], …",
    "TEXTSPLIT": "text, col_delimiter, [row_delimiter], [ignore_empty], …", "TIME": "hour, minute, second",
    "TODAY": "", "TOCOL": "array, [ignore], [scan_by_column]", "TOROW": "array, [ignore], [scan_by_column]",
    "TRANSPOSE": "array", "TREND": "known_y's, [known_x's], [new_x's], [const]", "TRIM": "text", "TRUNC": "number, [num_digits]",
    "UNIQUE": "array, [by_col], [exactly_once]", "UPPER": "text", "VALUE": "text", "VAR": "number1, [number2], …",
    "VAR.P": "number1, [number2], …", "VAR.S": "number1, [number2], …",
    "VLOOKUP": "lookup_value, table_array, col_index_num, [range_lookup]", "VSTACK": "array1, [array2], …",
    "WEEKDAY": "serial_number, [return_type]", "WEEKNUM": "serial_number, [return_type]",
    "WORKDAY": "start_date, days, [holidays]",
    "XLOOKUP": "lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]",
    "XMATCH": "lookup_value, lookup_array, [match_mode], [search_mode]", "XOR": "logical1, [logical2], …",
    "YEAR": "serial_number", "YEARFRAC": "start_date, end_date, [basis]",
    # CalcForge's own
    "VALUEIN": "quantity, unit", "INTERP": "x, known_x's, known_y's", "UNITOF": "quantity", "STRIPUNIT": "quantity",
}

# for the rest: the code's short names in plain words
WORDS = {"x": "value", "v": "value", "n": "number", "s": "text", "a": "value1", "b": "value2",
         "crit": "criteria", "ref": "range", "args": "value", "values": "value", "p": "probability",
         "sd": "standard_dev", "df": "deg_freedom", "lam": "lambda", "kind": "type", "fmt": "format",
         "xs": "known_x's", "ys": "known_y's", "d1": "deg_freedom1", "d2": "deg_freedom2"}
